language: node_js
node_js:
- iojs
- '7'
script:
  node Lambda_Func.js
cache:
  directories:
  - node_modules
deploy:
  provider: lambda
  function_name: stack_search
  region: us-east-2
  role: arn:aws:lambda:us-east-2:784849208592:function:stack_search
  runtime: nodejs4.3
  handler_name: handler
  access_key_id: AKIAJSPVXGCIC3HVRH6Q
  secret_acess_key:
    secure: JqZHDwwxRyfEueJzXf6mtzeWWbZOAXxr58fTm8VfshdDz8ttzfgYj1col7LV3o71VU+18sTvpEXn9SNIWvd3qmvwLhEYWuJb6figPEZ9Z7CNe8wtoTCFhvPzsXMk8Tqp7osoSMHKCRQcf7bttb5Xv/iJ3SSLghqqzSf4LiUxORDA+WSEcQIR6oWd8eeGOHiL1mGiS7XWJaf/xSE6If4y0laiYgB+lixU3QMgvZDODUHIMmK5ak60nY4/kOxnfHhrGIybo35k6bFpHvKRfvP2gZqE0AkYuajA8P8hoUJU3pBAzEQk90k42tf7ujUwsYcWubvOzAuiigR+IpgwuTCjhAs5qt/NAKK5N7cKsPqX2feENKGY/OfBKyjg+hNWqtf1DmLMCyz56NYFwMZbXXtyxmaqf+RV8TG3ANSC7nQ5c1vWnf06A6X0o8tAkFh0nfz6BSs45wn67lL3UakROlDqxGDw6orZC/HgyV8jvNKS2dXi66YCBIe/nykEhySOVWjMOEwZ5luMFAs6wAzZ26ymEiBPRCq0DGMdzmjlJvEA+/XxthxAb5CzwbE5xAIMZd6/Ao/wrLUbQ1JdnlgjlXMBzKN4FL3GHmPXi67gh+I0TT6tfVw97n7+2zZi8z5AgmBafj8cSIjpuChLsGZfPmP1P1tZnqT3OGB0+3Zk3aU6JCA=  
  on:
    branch: master
